# .github/labeler.yml

# 💡 ファイルパス → 自動でラベル付与
network-graph:
  - projects/from-rdb-to-network/fungi-network/**
tensorflow:
  - projects/tensorflowjs-playground/**
frontend:
  - projects/horizontal-scroll-emaki/**
docs:
  - docs/**
