# .github/DISCUSSION_TEMPLATE/project-idea.yml
categories:
  - Ideas
body:
  - type: markdown
    attributes:
      value: |
        💡 Thank you for proposing a new project idea!
        Please fill out the following prompts.
  - type: input
    id: title
    attributes:
      label: Project Title
  - type: textarea
    id: summary
    attributes:
      label: Summary of the idea
  - type: textarea
    id: goals
    attributes:
      label: What do you want to achieve?
  - type: textarea
    id: relevance
    attributes:
      label: How does it align with CANW?
