blank_issues_enabled: true
contact_links:
  - name: CANW Community Support
    url: https://github.com/satoshi-create/complexity-and-network-webdesign/discussions
    about: "Join community discussions or ask questions here."
  - name: CANW Documentation
    url: https://github.com/satoshi-create/complexity-and-network-webdesign/wiki
    about: "Check out the documentation for further details."
