# .github/workflows/auto-label.yml


# ワークフローの名前
name: Auto Label PRs
on:
  pull_request_target:
    types: [opened, synchronize, reopened] # PR作成・更新・再オープン時に発火！
    
#GitHub Token に書き込み権限を付与
permissions:
  contents: read
  pull-requests: write # ← PRにラベルを付けるには必須！

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4 #.github/labeler.yml を読み込む
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}" # GitHubのAPIトークン
