# .github/workflows/auto-label.yml

name: Auto Label PRs
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    
#GitHub Token に書き込み権限を付与
permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
